app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/planttracker/AreasActivity.java
app/src/main/java/com/example/planttracker/EditAreaActivity.java
app/src/main/java/com/example/planttracker/EditPlantActivity.java
app/src/main/java/com/example/planttracker/LoginActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/SignUpActivity.java
app/src/main/java/com/example/planttracker/ViewAreaActivity.java
app/src/main/java/com/example/planttracker/ViewPlantActivity.java
app/src/main/java/com/example/planttracker/database/AppDAO.java
app/src/main/java/com/example/planttracker/database/AppDatabase.java
app/src/main/java/com/example/planttracker/database/AppRepository.java
app/src/main/java/com/example/planttracker/database/entities/Area.java
app/src/main/java/com/example/planttracker/database/entities/Plant.java
app/src/main/java/com/example/planttracker/database/entities/User.java
app/src/main/java/com/example/planttracker/database/typeConverters/LightLevelTypeConverter.java
app/src/main/java/com/example/planttracker/database/typeConverters/LocalDateTimeTypeConverter.java
app/src/main/java/com/example/planttracker/utilities/LightLevel.java
app/src/main/res/layout/activity_areas.xml
app/src/main/res/layout/activity_edit_area.xml
app/src/main/res/layout/activity_edit_plant.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/activity_view_area.xml
app/src/main/res/layout/activity_view_plant.xml
gradle/libs.versions.toml

created the main files and basic structure of the project, added some initial TODOs to work on as first steps

initial-layout

---

app/src/main/java/com/example/planttracker/AdminActivity.java
app/src/main/java/com/example/planttracker/AreasActivity.java
app/src/main/java/com/example/planttracker/EditAreaActivity.java
app/src/main/java/com/example/planttracker/EditPlantActivity.java
app/src/main/java/com/example/planttracker/LoginActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/PlantsActivity.java
app/src/main/java/com/example/planttracker/SignUpActivity.java
app/src/main/java/com/example/planttracker/ViewAreaActivity.java
app/src/main/java/com/example/planttracker/ViewPlantActivity.java
app/src/main/res/layout/activity_view_area.xml
app/src/main/res/layout/activity_view_plant.xml
app/src/main/res/values/strings.xml

initial activity layouts completed, TODOs added to all Activity classes for onClick methods and intent factory methods

activity-todos

---

app/src/main/java/com/example/planttracker/database/entities/Area.java
app/src/main/java/com/example/planttracker/database/entities/User.java

finished the area entity class

area-entity-class

---

app/src/main/java/com/example/planttracker/database/AppDatabase.java
app/src/main/java/com/example/planttracker/database/typeConverters/LightLevelTypeConverter.java
app/src/main/java/com/example/planttracker/utilities/LightLevel.java

- implemented the LightLevelTypeConverter class 
- added a static method to LightLevels that converts an int to a light level value 
- added the LightLevelTypeConverter to the AppDatabase

LightLevelTypeConverter class

---

app/src/main/java/com/example/planttracker/database/AppRepository.java
app/src/main/java/com/example/planttracker/database/UserDAO.java

implemented the getRepository method in the AppRepository class, added insert and delete methods for all entities

getRepository method

---

app/src/main/java/com/example/planttracker/database/PlantDAO.java

deleted the addAllPlants method which had the wrong return type, and really wasn't necessary

getrepository-method

---

app/src/main/java/com/example/planttracker/ViewAreaActivity.java
app/src/main/java/com/example/planttracker/database/AppDatabase.java

Added Onclick methods for the edit button and the back button. Created a basic IntentFactory. The back button onClick method is currently commented out, it is implemented prior to the implementation of AreasActivityIntentFactory.

Added onClick methods for edit and back buttons and a basic IntentFactory

---

app/src/main/java/com/example/planttracker/AdminActivity.java
app/src/main/java/com/example/planttracker/AreasActivity.java
app/src/main/java/com/example/planttracker/LoginActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/PlantsActivity.java

implemented intent factory for MainActivity and onClick methods for My Plants, My Areas, and Admin Options buttons

MainActivity intent factory and onClicks

---

app/src/main/java/com/example/planttracker/EditAreaActivity.java
app/src/main/java/com/example/planttracker/ViewAreaActivity.java

Added basic functionality to EditAreaActivity.java, onClick methods save, cancel and delete buttons. Added a basic IntentFactory. Commented out the delete button due it being implemented prior to AreasActivityIntetnFactory.

EditAreaActivity basic onClick functionality and basic IntentFactory. 

---

app/src/main/java/com/example/planttracker/AdminActivity.java
app/src/main/java/com/example/planttracker/AreasActivity.java
app/src/main/java/com/example/planttracker/EditAreaActivity.java
app/src/main/java/com/example/planttracker/EditPlantActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/PlantsActivity.java
app/src/main/java/com/example/planttracker/ViewPlantActivity.java
app/src/main/res/layout/activity_areas.xml
app/src/main/res/layout/activity_plants.xml

implemented intent factory for AreasActivity and PlantsActivity and onClick methods for all buttons

AreasActivity and PlantsActivity

---

app/src/main/java/com/example/planttracker/LoginActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/SignUpActivity.java
app/src/main/java/com/example/planttracker/database/UserDAO.java
gradle/libs.versions.toml

#31: LoginActivity
- Created a basic intent factory method
- Created onClick method for the Login button that launches MainActivity
- Created onClick method for the Create Account button that launches SignUpActivity
#34: SignUpActivity
- Created a basic intent factory method
- Created onClick method for the Sign Up button that launches LoginActivity (or should this go directly to MainActivity?)
- Created onClick method for the Cancel button that launches LoginActivity

Completed implementing issue #31 and #34.

---

app/src/main/java/com/example/planttracker/AdminActivity.java
app/src/main/java/com/example/planttracker/LoginActivity.java
app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/SignUpActivity.java
app/src/main/java/com/example/planttracker/database/AppDatabase.java
app/src/main/java/com/example/planttracker/database/AppRepository.java
app/src/main/java/com/example/planttracker/database/UserDAO.java
app/src/main/java/com/example/planttracker/database/entities/User.java
app/src/main/res/menu/user_menu.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

Added an action bar, idk why the database is not getting created

logout_menu

---

app/src/main/java/com/example/planttracker/MainActivity.java
app/src/main/java/com/example/planttracker/SignUpActivity.java
app/src/main/java/com/example/planttracker/database/AppRepository.java
app/src/main/java/com/example/planttracker/database/UserDAO.java

Completed user signup and login screen. Updated AppRepository to check if a username exists during signup. Updated login screen to fetch credentials from database. Tested and verified that the added functionality works as expected.

Signup and Login

---

app/src/main/java/com/example/planttracker/ViewPlantActivity.java

Completed implementing Issue #36

36-viewPlantActivity-IntentFactory-and-OnClick

---

app/src/main/java/com/example/planttracker/EditPlantActivity.java
app/src/main/java/com/example/planttracker/ViewPlantActivity.java

Implemented onClick redirects for EditPlantActivity; basic intent factory already built. Will build out functionality in future pull.

30 edit plant activity intent factory and on click

---

app/src/main/java/com/example/planttracker/ViewAreaActivity.java
app/src/main/java/com/example/planttracker/database/AppRepository.java
app/src/main/java/com/example/planttracker/database/AreaDAO.java
app/src/main/res/values/strings.xml

Completed functionality of ViewAreaActivity.java. so that in theory it updates the text of textView according to the selected plant. Further testing is needed to make sure it is working as intended. Edited AreaDao to get an area by areaID. Edited AppRepository.java to reflect that change.

ViewAreaActivity added functionality. Further testing may be needed. 

---

app/src/main/java/com/example/planttracker/ViewAreaActivity.java

changed ViewAreaActivity.java line 94, to handle null value. App crashed before. More testing needed.

Changed line 94 and 48 of ViewAreaActivity.java

---

app/src/main/java/com/example/planttracker/ViewPlantActivity.java

Non-underlined error on line 61:
'setOnclickListener(android.view.View.OnClickListener)' in 'android.view.View' cannot be applied to '()'
Advice welcome!

65 view plant activity functionality

---

app/src/main/java/com/example/planttracker/EditPlantActivity.java

Fixed bug in EditPlantActivity that was redirecting to empty ViewPlantActivity page following creation of new Plant.

Issue 94: Minor Bug Fix

---

app/src/main/java/com/example/planttracker/EditAreaActivity.java

Fixed bug in EditAreasActivity that was redirecting to empty ViewAreaActivity page following creation of new Area.

Issue 95: Minor Bug Fix

---

app/src/main/java/com/example/planttracker/EditAreaActivity.java

…error message if no name is entered for the area.

Issue 96: Data Validation for EditAreaActivity
